-- Add up migration script here
-- Inserting data for Apple
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4FbWJcJCAq2zy3zisQcwXZ9qDsVymFjmdQ7Pw93xBrNBfDD87-bQy7TtDqlMCCDG8QvE&usqp=CAU', 'Apple', 'Technology', 'Cupertino, CA', '1976', 'https://twitter.com/apple', 'https://www.apple.com/', 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories.', 'Technology', 154000, 'One Apple Park Way, Cupertino, CA', 'Consumer Electronics', '{"https://img.freepik.com/free-photo/modern-office-space-with-desktops-with-modern-computers-created-with-generative-ai-technology_185193-110089.jpg", "https://images.unsplash.com/photo-1606857521015-7f9fcf423740?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG9mZmljZXxlbnwwfHwwfHx8MA%3D%3D", "https://allthedifferences.com/wp-content/uploads/2022/04/campaign-creators-gMsnXqILjp4-unsplash-1-728x546.jpg.webp"}');

-- Inserting data for Microsoft
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRxPPk6F0_8xW8vYMft-VkSSlfZAuaAFYxGhGGocQHkwEgBR2--OiD0yR7xAxsp', 'Microsoft', 'Technology', 'Redmond, WA', '1975', 'https://twitter.com/Microsoft', 'https://www.microsoft.com/', 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide.', 'Technology', 181000, 'One Microsoft Way, Redmond, WA', 'Software', '{"https://image.cnbcfm.com/api/v1/image/107032274-1647540069295-gettyimages-1084167640-2018_10_13-n1_office_0312.jpeg?v=1647540545", "https://plus.unsplash.com/premium_photo-1661775434014-9c0e8d71de03?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8b2ZmaWNlfGVufDB8fDB8fHww"}');

-- Inserting data for Google
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png', 'Google', 'Technology', 'Mountain View, CA', '1998', 'https://twitter.com/Google', 'https://www.google.com/', 'Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware.', 'Technology', 150000, '1600 Amphitheatre Parkway, Mountain View, CA', 'Internet', '{"https://cdn-dynmedia-1.microsoft.com/is/image/microsoftcorp/O2019-Hero-image-x2:VP1-539x440?resMode=sharp2&op_usm=1.5,0.65,15,0&wid=1920&hei=720&qlt=75&fit=constrain"}');

-- Inserting data for Amazon
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS11p243c488ivHF8766gBSNdWvHsjIVuOzwGXiu1peuznsDp-wHSOZeC9yZC9r', 'Amazon', 'Technology', 'Seattle, WA', '1994', 'https://twitter.com/amazon', 'https://www.amazon.com/', 'Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence.', 'Technology', 1530000, '410 Terry Ave N, Seattle, WA', 'E-commerce', '{"https://allthedifferences.com/wp-content/uploads/2022/04/campaign-creators-gMsnXqILjp4-unsplash-1-728x546.jpg.webp"}');

-- Inserting data for Facebook
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://cdn3.iconfinder.com/data/icons/picons-social/57/46-facebook-512.png', 'Facebook', 'Technology', 'Menlo Park, CA', '2004', 'https://twitter.com/facebook', 'https://www.facebook.com/', 'Facebook, Inc. is an American social media conglomerate corporation founded on February 4, 2004, by Mark Zuckerberg.', 'Technology', 63000, '1 Hacker Way, Menlo Park, CA', 'Social Media', '{"https://img.freepik.com/free-photo/modern-office-space-with-desktops-with-modern-computers-created-with-generative-ai-technology_185193-110089.jpg"}');

-- Inserting data for Tesla
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSXUs65jZelegc9kG5xzUzDEhJ-LJeCEy_hIcNkw5TNe5bQLplTg75T-J8OdIE3', 'Tesla', 'Automotive', 'Palo Alto, CA', '2003', 'https://twitter.com/Tesla', 'https://www.tesla.com/', 'Tesla, Inc. is an American electric vehicle and clean energy company based in Palo Alto, California.', 'Automotive', 70000, '3500 Deer Creek Rd, Palo Alto, CA', 'Electric Vehicles', '{"https://images.unsplash.com/photo-1606857521015-7f9fcf423740?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG9mZmljZXxlbnwwfHwwfHx8MA%3D%3D", "https://allthedifferences.com/wp-content/uploads/2022/04/campaign-creators-gMsnXqILjp4-unsplash-1-728x546.jpg.webp"}');

-- Inserting data for Broadcom
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRcJdEFLghJ_uke74u23BzYBaQrtV5ECfanWjfdV1iMWjeyFszOZvrSHaI61Dis', 'Broadcom', 'Technology', 'San Jose, CA', '1961', 'https://twitter.com/Broadcom', 'https://www.broadcom.com/', 'Broadcom Inc. is an American designer, developer, manufacturer and global supplier of a wide range of semiconductor and infrastructure software solutions.', 'Technology', 19000, '1320 Ridder Park Dr, San Jose, CA', 'Semiconductors', '{"https://img.freepik.com/free-photo/modern-office-space-with-desktops-with-modern-computers-created-with-generative-ai-technology_185193-110089.jpg"}');

-- Inserting data for Samsung
INSERT INTO companies ( company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://cdn.iconscout.com/icon/free/png-256/free-samsung-226432.png', 'Samsung', 'Technology', 'Seoul, South Korea', '1938', 'https://twitter.com/Samsung', 'https://www.samsung.com/', 'Samsung Electronics Co., Ltd. is a South Korean multinational electronics company headquartered in the Yeongtong District of Suwon.', 'Technology', 287000, '129 Samsung-ro, Yeongtong-gu, Suwon-si, Gyeonggi-do, South Korea', 'Consumer Electronics', '{"https://img.freepik.com/free-photo/modern-office-space-with-desktops-with-modern-computers-created-with-generative-ai-technology_185193-110089.jpg"}');

-- Inserting data for Oracle
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtjw-bI_VbdEDpT2yKyTw21e9Xw2D6EsbtfKon-MWsBED-2UB2OsLBXFIofjaf', 'Oracle', 'Technology', 'Redwood City, CA', '1977', 'https://twitter.com/Oracle', 'https://www.oracle.com/', 'Oracle Corporation is an American multinational computer technology corporation headquartered in Redwood Shores, California.', 'Technology', 135000, '500 Oracle Pkwy, Redwood City, CA', 'Software', '{"https://image.cnbcfm.com/api/v1/image/107032274-1647540069295-gettyimages-1084167640-2018_10_13-n1_office_0312.jpeg?v=1647540545"}');

-- Inserting data for Tencent Holdings Limited
INSERT INTO companies (company_image_url, company_name, category, location, year_created, social_link, website_link, about, industry, employee_size, heads_office_address, specialization, company_other_images)
VALUES ('https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ5KZDv8igB8R0qvrN0ncQwBSwXeQWCH3m6cQYBtmyqNi56qKywoVAJduZuiivJ', 'Tencent Holdings Limited', 'Technology', 'Shenzhen, China', '1998', 'https://twitter.com/TencentGlobal', 'https://www.tencent.com/', 'Tencent Holdings Limited is a Chinese multinational conglomerate holding company founded in 1998, whose subsidiaries specialise in various Internet-related services and products, entertainment, artificial intelligence and technology.', 'Technology', 87000, 'Tencent Building, Kejizhongyi Avenue, Nanshan District, Shenzhen, China', 'Internet', '{"https://plus.unsplash.com/premium_photo-1661775434014-9c0e8d71de03?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8b2ZmaWNlfGVufDB8fDB8fHww"}');

